[build]
  command = "./netlify-build.sh"
  publish = "netlify-dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  BUN_INSTALL = "true"
  # Set working directory for build
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"

# Handle Next.js routing with internationalization
# Priority order for redirects matters!

# 1. API routes first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# 2. Handle Next.js static files
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/.netlify/functions/server"
  status = 200

# 3. Handle all page requests through Next.js server (for standalone mode)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# 4. Special handling for static assets
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/logo.svg"
  to = "/logo.svg"
  status = 200

# Handle static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Functions configuration
[functions]
  node_bundler = "esbuild"
  directory = "functions"

[dev]
  command = "cd saasfly && bun run dev"
  port = 3000
  publish = "saasfly/apps/nextjs/.next"