[build]
  command = "./netlify-build-simple.sh"
  publish = "netlify-dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  BUN_INSTALL = "true"
  # Set working directory for build
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"

# Simple static site configuration for now
# All files will be served directly

# Static assets
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[dev]
  command = "cd saasfly && bun run dev"
  port = 3000
  publish = "saasfly/apps/nextjs/.next"