[build]
  command = "./netlify-build-nextjs.sh"
  publish = "netlify-dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  BUN_INSTALL = "true"
  # Set working directory for build
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"
  # Next.js build settings
  NEXT_TELEMETRY_DISABLED = "1"
  SKIP_ENV_VALIDATION = "true"

# Next.js static routing configuration
[[redirects]]
  from = "/_next/static/*"
  to = "/apps/nextjs/.next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Handle locale routing - redirect to HTML files
[[redirects]]
  from = "/zh"
  to = "/zh/index.html"
  status = 200

[[redirects]]
  from = "/zh/*"
  to = "/zh/:splat.html"
  status = 200

[[redirects]]
  from = "/en"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/:splat.html"
  status = 200

[[redirects]]
  from = "/ko"
  to = "/ko/index.html"
  status = 200

[[redirects]]
  from = "/ko/*"
  to = "/ko/:splat.html"
  status = 200

[[redirects]]
  from = "/ja"
  to = "/ja/index.html"
  status = 200

[[redirects]]
  from = "/ja/*"
  to = "/ja/:splat.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat.html"
  status = 200

# Root redirect
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Catch all for dynamic routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Static assets
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[dev]
  command = "cd saasfly && bun run dev"
  port = 3000
  publish = "saasfly/apps/nextjs/.next"